# Generated by Django 5.2.15 on 2026-06-12 12:52

import core.validators
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(help_text='Required. 3-20 characters. Letters, numbers, and underscores only.', max_length=20, unique=True, validators=[core.validators.validate_username], verbose_name='username')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if user has verified badge', verbose_name='verified')),
                ('is_premium', models.BooleanField(default=False, help_text='Indicates if user has premium subscription', verbose_name='premium')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA enabled')),
                ('two_factor_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='2FA secret')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='suspended')),
                ('suspension_reason', models.TextField(blank=True, null=True, verbose_name='suspension reason')),
                ('suspended_until', models.DateTimeField(blank=True, null=True, verbose_name='suspended until')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='last active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'follow',
                'verbose_name_plural': 'follows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to=settings.AUTH_USER_MODEL)),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mute',
                'verbose_name_plural': 'mutes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='display name')),
                ('bio', models.TextField(blank=True, max_length=160, verbose_name='bio')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='website')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='banner')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=10, verbose_name='theme')),
                ('is_private', models.BooleanField(default=False, verbose_name='private account')),
                ('show_media', models.BooleanField(default=True, verbose_name='show media in profile')),
                ('allow_mentions', models.BooleanField(default=True, verbose_name='allow mentions')),
                ('allow_dms', models.BooleanField(default=True, verbose_name='allow direct messages')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='push notifications')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='followers count')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='following count')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='posts count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='accounts_us_is_veri_fa45d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_premium'], name='accounts_us_is_prem_25436c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', '-created_at'], name='accounts_fo_followe_592424_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', '-created_at'], name='accounts_fo_followi_0cee87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='mute',
            unique_together={('muter', 'muted')},
        ),
    ]
